"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IRender__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "bytes",
                name: "_data",
                type: "bytes"
            },
            {
                internalType: "uint16",
                name: "destLen",
                type: "uint16"
            },
            {
                internalType: "string",
                name: "name",
                type: "string"
            },
        ],
        name: "addToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256"
            },
        ],
        name: "tokenURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var IRender__factory = /** @class */ (function () {
    function IRender__factory() {
    }
    IRender__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IRender__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IRender__factory.abi = _abi;
    return IRender__factory;
}());
exports.IRender__factory = IRender__factory;
