/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IExquisiteGraphics,
  IExquisiteGraphicsInterface,
} from "../../../contracts/interfaces/IExquisiteGraphics";

const _abi = [
  {
    inputs: [],
    name: "BackgroundColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColors",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxColumns",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxPixels",
    type: "error",
  },
  {
    inputs: [],
    name: "ExceededMaxRows",
    type: "error",
  },
  {
    inputs: [],
    name: "MissingHeader",
    type: "error",
  },
  {
    inputs: [],
    name: "NoColors",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughData",
    type: "error",
  },
  {
    inputs: [],
    name: "PixelColorIndexOutOfRange",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes3[]",
            name: "colors",
            type: "bytes3[]",
          },
          {
            internalType: "enum IExquisiteGraphics.PaletteTypes",
            name: "paletteType",
            type: "uint8",
          },
        ],
        internalType: "struct IExquisiteGraphics.Palette",
        name: "palette",
        type: "tuple",
      },
      {
        internalType: "uint8",
        name: "xOffset",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "yOffset",
        type: "uint8",
      },
    ],
    name: "drawPixels",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "getDimensions",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IExquisiteGraphics__factory {
  static readonly abi = _abi;
  static createInterface(): IExquisiteGraphicsInterface {
    return new utils.Interface(_abi) as IExquisiteGraphicsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExquisiteGraphics {
    return new Contract(address, _abi, signerOrProvider) as IExquisiteGraphics;
  }
}
