"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IInflator__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "bytes",
                name: "source",
                type: "bytes"
            },
            {
                internalType: "uint256",
                name: "destlen",
                type: "uint256"
            },
        ],
        name: "puff",
        outputs: [
            {
                internalType: "enum Inflate.ErrorCode",
                name: "",
                type: "uint8"
            },
            {
                internalType: "bytes",
                name: "",
                type: "bytes"
            },
        ],
        stateMutability: "pure",
        type: "function"
    },
];
var IInflator__factory = /** @class */ (function () {
    function IInflator__factory() {
    }
    IInflator__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IInflator__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IInflator__factory.abi = _abi;
    return IInflator__factory;
}());
exports.IInflator__factory = IInflator__factory;
