/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IExquisiteGraphics {
  export type PaletteStruct = {
    colors: PromiseOrValue<BytesLike>[];
    paletteType: PromiseOrValue<BigNumberish>;
  };

  export type PaletteStructOutput = [string[], number] & {
    colors: string[];
    paletteType: number;
  };
}

export interface ExquisiteGraphicsInterface extends utils.Interface {
  functions: {
    "drawPixels(bytes,(bytes3[],uint8),uint8,uint8)": FunctionFragment;
    "getDimensions(bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "drawPixels" | "getDimensions"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "drawPixels",
    values: [
      PromiseOrValue<BytesLike>,
      IExquisiteGraphics.PaletteStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getDimensions",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "drawPixels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDimensions",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ExquisiteGraphics extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExquisiteGraphicsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    drawPixels(
      data: PromiseOrValue<BytesLike>,
      palette: IExquisiteGraphics.PaletteStruct,
      xOffset: PromiseOrValue<BigNumberish>,
      yOffset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getDimensions(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number, number]>;
  };

  drawPixels(
    data: PromiseOrValue<BytesLike>,
    palette: IExquisiteGraphics.PaletteStruct,
    xOffset: PromiseOrValue<BigNumberish>,
    yOffset: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getDimensions(
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[number, number]>;

  callStatic: {
    drawPixels(
      data: PromiseOrValue<BytesLike>,
      palette: IExquisiteGraphics.PaletteStruct,
      xOffset: PromiseOrValue<BigNumberish>,
      yOffset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getDimensions(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number, number]>;
  };

  filters: {};

  estimateGas: {
    drawPixels(
      data: PromiseOrValue<BytesLike>,
      palette: IExquisiteGraphics.PaletteStruct,
      xOffset: PromiseOrValue<BigNumberish>,
      yOffset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDimensions(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    drawPixels(
      data: PromiseOrValue<BytesLike>,
      palette: IExquisiteGraphics.PaletteStruct,
      xOffset: PromiseOrValue<BigNumberish>,
      yOffset: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDimensions(
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
