/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CCZooRender } from "./CCZooRender";
export type { ICCZPayment } from "./ICCZPayment";
export type { ICCZooMain } from "./ICCZooMain";
export type { IInflator } from "./IInflator";
