"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.ICCZooRenderer__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256"
            },
        ],
        name: "tokenURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var ICCZooRenderer__factory = /** @class */ (function () {
    function ICCZooRenderer__factory() {
    }
    ICCZooRenderer__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ICCZooRenderer__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ICCZooRenderer__factory.abi = _abi;
    return ICCZooRenderer__factory;
}());
exports.ICCZooRenderer__factory = ICCZooRenderer__factory;
