/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICCZPayment,
  ICCZPaymentInterface,
} from "../../../contracts/CCZoo.sol/ICCZPayment";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "shares_",
        type: "uint256",
      },
    ],
    name: "addPayee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICCZPayment__factory {
  static readonly abi = _abi;
  static createInterface(): ICCZPaymentInterface {
    return new utils.Interface(_abi) as ICCZPaymentInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICCZPayment {
    return new Contract(address, _abi, signerOrProvider) as ICCZPayment;
  }
}
