/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICCZooRenderer,
  ICCZooRendererInterface,
} from "../../../contracts/CCZoo.sol/ICCZooRenderer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICCZooRenderer__factory {
  static readonly abi = _abi;
  static createInterface(): ICCZooRendererInterface {
    return new utils.Interface(_abi) as ICCZooRendererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICCZooRenderer {
    return new Contract(address, _abi, signerOrProvider) as ICCZooRenderer;
  }
}
