"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.ICCZooRenderer__factory = exports.CCZoo__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CCZoo__factory_1 = require("./CCZoo__factory");
__createBinding(exports, CCZoo__factory_1, "CCZoo__factory");
var ICCZooRenderer__factory_1 = require("./ICCZooRenderer__factory");
__createBinding(exports, ICCZooRenderer__factory_1, "ICCZooRenderer__factory");
