/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Collage } from "./Collage";
export type { IPieces } from "./IPieces";
export type { IRender } from "./IRender";
