/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ERC721G {
  export type LayerStructStruct = {
    layerId: PromiseOrValue<BigNumberish>;
    xOffset: PromiseOrValue<BigNumberish>;
    yOffset: PromiseOrValue<BigNumberish>;
  };

  export type LayerStructStructOutput = [number, number, number] & {
    layerId: number;
    xOffset: number;
    yOffset: number;
  };
}

export interface IRenderInterface extends utils.Interface {
  functions: {
    "previewCollage(tuple[4])": FunctionFragment;
    "tokenURI(uint256,tuple[4])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "previewCollage" | "tokenURI"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "previewCollage",
    values: [
      [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [
      PromiseOrValue<BigNumberish>,
      [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "previewCollage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;

  events: {};
}

export interface IRender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRenderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    previewCollage(
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<[string]>;

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  previewCollage(
    layerIds: [
      ERC721G.LayerStructStruct,
      ERC721G.LayerStructStruct,
      ERC721G.LayerStructStruct,
      ERC721G.LayerStructStruct
    ],
    overrides?: CallOverrides
  ): Promise<string>;

  tokenURI(
    tokenId: PromiseOrValue<BigNumberish>,
    layerIds: [
      ERC721G.LayerStructStruct,
      ERC721G.LayerStructStruct,
      ERC721G.LayerStructStruct,
      ERC721G.LayerStructStruct
    ],
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    previewCollage(
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<string>;

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    previewCollage(
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    previewCollage(
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      layerIds: [
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct,
        ERC721G.LayerStructStruct
      ],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
