"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.OwnableUpgradeable__factory = exports.IAccessControlUpgradeable__factory = exports.AccessControlUpgradeable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AccessControlUpgradeable__factory_1 = require("./AccessControlUpgradeable__factory");
__createBinding(exports, AccessControlUpgradeable__factory_1, "AccessControlUpgradeable__factory");
var IAccessControlUpgradeable__factory_1 = require("./IAccessControlUpgradeable__factory");
__createBinding(exports, IAccessControlUpgradeable__factory_1, "IAccessControlUpgradeable__factory");
var OwnableUpgradeable__factory_1 = require("./OwnableUpgradeable__factory");
__createBinding(exports, OwnableUpgradeable__factory_1, "OwnableUpgradeable__factory");
