/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IInflator__factory } from "./IInflator__factory";
export { Render__factory } from "./Render__factory";
