/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPieces,
  IPiecesInterface,
} from "../../../contracts/Render.sol/IPieces";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getLayerData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "uint8",
            name: "maxSupply",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "supplyMinted",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "royalties",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "maxPerWallet",
            type: "uint8",
          },
          {
            internalType: "uint64",
            name: "price",
            type: "uint64",
          },
        ],
        internalType: "struct SharedStructs.LayerInfo",
        name: "",
        type: "tuple",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPieces__factory {
  static readonly abi = _abi;
  static createInterface(): IPiecesInterface {
    return new utils.Interface(_abi) as IPiecesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPieces {
    return new Contract(address, _abi, signerOrProvider) as IPieces;
  }
}
