"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.IRender__factory = exports.IPieces__factory = exports.Collage__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Collage__factory_1 = require("./Collage__factory");
__createBinding(exports, Collage__factory_1, "Collage__factory");
var IPieces__factory_1 = require("./IPieces__factory");
__createBinding(exports, IPieces__factory_1, "IPieces__factory");
var IRender__factory_1 = require("./IRender__factory");
__createBinding(exports, IRender__factory_1, "IRender__factory");
