/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Collage__factory } from "./Collage__factory";
export { IPieces__factory } from "./IPieces__factory";
export { IRender__factory } from "./IRender__factory";
