/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPieces,
  IPiecesInterface,
} from "../../../contracts/Collage.sol/IPieces";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16[16]",
        name: "layerIds",
        type: "uint16[16]",
      },
    ],
    name: "getPriceAndBurn",
    outputs: [
      {
        internalType: "uint256",
        name: "totalPrice",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPieces__factory {
  static readonly abi = _abi;
  static createInterface(): IPiecesInterface {
    return new utils.Interface(_abi) as IPiecesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPieces {
    return new Contract(address, _abi, signerOrProvider) as IPieces;
  }
}
