"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IPieces__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "account",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "id",
                type: "uint256"
            },
            {
                internalType: "uint256",
                name: "value",
                type: "uint256"
            },
        ],
        name: "burn",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var IPieces__factory = /** @class */ (function () {
    function IPieces__factory() {
    }
    IPieces__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IPieces__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IPieces__factory.abi = _abi;
    return IPieces__factory;
}());
exports.IPieces__factory = IPieces__factory;
