/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRender,
  IRenderInterface,
} from "../../../contracts/Collage.sol/IRender";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "layerId",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "xOffset",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "yOffset",
            type: "uint8",
          },
        ],
        internalType: "struct ERC721G.LayerStruct[4]",
        name: "layerIds",
        type: "tuple[4]",
      },
      {
        internalType: "uint8",
        name: "layerNr",
        type: "uint8",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "layerId",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "xOffset",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "yOffset",
            type: "uint8",
          },
        ],
        internalType: "struct ERC721G.LayerStruct",
        name: "newLayer",
        type: "tuple",
      },
    ],
    name: "previewCollage",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint8",
            name: "layerId",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "xOffset",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "yOffset",
            type: "uint8",
          },
        ],
        internalType: "struct ERC721G.LayerStruct[4]",
        name: "layerIds",
        type: "tuple[4]",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRender__factory {
  static readonly abi = _abi;
  static createInterface(): IRenderInterface {
    return new utils.Interface(_abi) as IRenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRender {
    return new Contract(address, _abi, signerOrProvider) as IRender;
  }
}
