"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IRender__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                components: [
                    {
                        internalType: "uint8",
                        name: "layerId",
                        type: "uint8"
                    },
                    {
                        internalType: "uint8",
                        name: "xOffset",
                        type: "uint8"
                    },
                    {
                        internalType: "uint8",
                        name: "yOffset",
                        type: "uint8"
                    },
                ],
                internalType: "struct ERC721G.LayerStruct[4]",
                name: "layerIds",
                type: "tuple[4]"
            },
            {
                internalType: "uint8",
                name: "layerNr",
                type: "uint8"
            },
            {
                components: [
                    {
                        internalType: "uint8",
                        name: "layerId",
                        type: "uint8"
                    },
                    {
                        internalType: "uint8",
                        name: "xOffset",
                        type: "uint8"
                    },
                    {
                        internalType: "uint8",
                        name: "yOffset",
                        type: "uint8"
                    },
                ],
                internalType: "struct ERC721G.LayerStruct",
                name: "newLayer",
                type: "tuple"
            },
        ],
        name: "previewCollage",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256"
            },
            {
                components: [
                    {
                        internalType: "uint8",
                        name: "layerId",
                        type: "uint8"
                    },
                    {
                        internalType: "uint8",
                        name: "xOffset",
                        type: "uint8"
                    },
                    {
                        internalType: "uint8",
                        name: "yOffset",
                        type: "uint8"
                    },
                ],
                internalType: "struct ERC721G.LayerStruct[4]",
                name: "layerIds",
                type: "tuple[4]"
            },
        ],
        name: "tokenURI",
        outputs: [
            {
                internalType: "string",
                name: "",
                type: "string"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var IRender__factory = /** @class */ (function () {
    function IRender__factory() {
    }
    IRender__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IRender__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IRender__factory.abi = _abi;
    return IRender__factory;
}());
exports.IRender__factory = IRender__factory;
