/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICCZooMain,
  ICCZooMainInterface,
} from "../../../contracts/CCZooRender.sol/ICCZooMain";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getMetadataHash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICCZooMain__factory {
  static readonly abi = _abi;
  static createInterface(): ICCZooMainInterface {
    return new utils.Interface(_abi) as ICCZooMainInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICCZooMain {
    return new Contract(address, _abi, signerOrProvider) as ICCZooMain;
  }
}
