"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.IInflator__factory = exports.ICCZooMain__factory = exports.ICCZPayment__factory = exports.CCZooRender__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CCZooRender__factory_1 = require("./CCZooRender__factory");
__createBinding(exports, CCZooRender__factory_1, "CCZooRender__factory");
var ICCZPayment__factory_1 = require("./ICCZPayment__factory");
__createBinding(exports, ICCZPayment__factory_1, "ICCZPayment__factory");
var ICCZooMain__factory_1 = require("./ICCZooMain__factory");
__createBinding(exports, ICCZooMain__factory_1, "ICCZooMain__factory");
var IInflator__factory_1 = require("./IInflator__factory");
__createBinding(exports, IInflator__factory_1, "IInflator__factory");
