"use strict";
exports.__esModule = true;
exports.draftIerc20PermitSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.draftIerc20PermitSol = require("./draft-IERC20Permit.sol");
