"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.IERC1155MetadataURIUpgradeable__factory = exports.ERC1155SupplyUpgradeable__factory = exports.ERC1155BurnableUpgradeable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ERC1155BurnableUpgradeable__factory_1 = require("./ERC1155BurnableUpgradeable__factory");
__createBinding(exports, ERC1155BurnableUpgradeable__factory_1, "ERC1155BurnableUpgradeable__factory");
var ERC1155SupplyUpgradeable__factory_1 = require("./ERC1155SupplyUpgradeable__factory");
__createBinding(exports, ERC1155SupplyUpgradeable__factory_1, "ERC1155SupplyUpgradeable__factory");
var IERC1155MetadataURIUpgradeable__factory_1 = require("./IERC1155MetadataURIUpgradeable__factory");
__createBinding(exports, IERC1155MetadataURIUpgradeable__factory_1, "IERC1155MetadataURIUpgradeable__factory");
