/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace SharedStructs {
  export type LayerInfoStruct = {
    creator: PromiseOrValue<string>;
    maxSupply: PromiseOrValue<BigNumberish>;
    supplyMinted: PromiseOrValue<BigNumberish>;
    royalties: PromiseOrValue<BigNumberish>;
    maxPerWallet: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
  };

  export type LayerInfoStructOutput = [
    string,
    number,
    number,
    number,
    number,
    BigNumber
  ] & {
    creator: string;
    maxSupply: number;
    supplyMinted: number;
    royalties: number;
    maxPerWallet: number;
    price: BigNumber;
  };
}

export interface IPiecesInterface extends utils.Interface {
  functions: {
    "getLayerData(uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getLayerData"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLayerData",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLayerData",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPieces extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPiecesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLayerData(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructs.LayerInfoStructOutput, string]>;
  };

  getLayerData(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[SharedStructs.LayerInfoStructOutput, string]>;

  callStatic: {
    getLayerData(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SharedStructs.LayerInfoStructOutput, string]>;
  };

  filters: {};

  estimateGas: {
    getLayerData(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getLayerData(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
